# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-GB # Set the site language
title: Creative Prediction with Neural Networks
logo: "/assets/network_logo.svg" # Site logo, also used in jekyll-seo-tag
email: charlepm@ifi.uio.no
repo: "https://github.com/cpmpercussion/creative-rediction"

description: >- # this means to ignore newlines until "baseurl:"
  Tutorials and Examples for Artistic Deep Learning 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://creativeprediction.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cpmpercussion
github_username:  cpmpercussion
# show_downloads: true
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference


# Build settings
markdown: kramdown
# theme: minima
remote_theme: daviddarnes/alembic
# theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed

navigation_header:
  Home: /
  NIME: /nime/
  Tutorials: /tutorials/
  Presentations: /presentations/
  IMPS: /imps/
  Blog: /blog/
  Setup: /setup/

navigation_footer:
  Created by Charles Martin: https://charlesmartin.com.au
  Part of EPEC (RCN Project no. 240862): https://www.hf.uio.no/ritmo/english/projects/all/epec/
  Part of the RTMO Centre for Interdisciplinary Studies in Rhythm Time and Motion (RCN Project no. 262762): https://www.hf.uio.no/ritmo/english/
  Supported by COINMAC (RCN Project no. 261645): https://www.mn.uio.no/ifi/english/research/projects/coinmac/index.html
